default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        sync_job:
          class: SyncJob
          schedule: "every minute"
  workers:
    - queues: "default"
      threads: 5
      processes: 1
      polling_interval: 0.1
    - queues: "transcribe"
      threads: 1
      processes: 1
      polling_interval: 0.1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
